server:
  port: 8080
spring:
  application:
    name: users
  mongodb:
    host: mongodb_server
    port: 27017
    database: db_users
    username: admin
    password: password123
    authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: health