server:
  port: 8082
spring:
  application:
    name: orders
  mongodb:
    host: 127.0.0.1
    port: 27017
    database: db_users
    username: admin
    password: password123
    authentication-database: admin