server:
  port: 8085

spring:
  application:
    name: aggregator

services:
  users:
    url: http://users-service:8080
  products:
    url: http://products-service:8081
  orders:
    url: http://orders-service:8082
